### PR TITLE
Do not point to docs in site_branding_link by default (bnc#917665)

### PR DESCRIPTION
**Pull request by vuntz**
This hardly makes sense, and the default from Horizon is much saner.

https://bugzilla.suse.com/show_bug.cgi?id=917665

### CODE REVIEW

**Comment by toabctl** [comment]
Hm. This still doesn't explain why ```SITE_BRANDING_LINK``` was set to ```"/help/"```, does it? Anyway. Changing ```site_branding_link``` in the raw view to ```""``` fixes the problem and points the logo to ```/home/``` which is fine.

**Comment by vuntz** [comment]
> Hm. This still doesn't explain why ```SITE_BRANDING_LINK``` was set to ```"/help/"```, does it?

That was a patch in our package :-)

**Comment by toabctl** [comment]
+1

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
