### PR TITLE
Fix schema and template broken in PR#218

### PR DESCRIPTION
**Pull request by aplanas**
* Fix bc-template-nova_dashboard.schema mapping
* Fix template tag in local_settings.py

### CODE REVIEW

**Comment by vuntz** [comment]
Ouch. Not sure how I didn't notice that :/

+1

**Comment by rhafer** [comment]
+1

**Comment by aplanas** [comment]
Thanks and sorry

**Comment by rsalevsky** [comment]
Issue is fixed :+1:

**Pull request merged**
