### PR TITLE
Fix quoting of supported_provider_types (bsc#936368)

### PR DESCRIPTION
**Pull request by dirkmueller**
Otherwise in case it is not a valid python identifer,
start of dashboard will fail.

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Comment by bmwiedemann** [comment]
mhh... in the default case, this produces 'supported_provider_types': '["gre", "vlan"]',

**Comment by dirkmueller** [comment]
@bmwiedemann ah, good point, so thats why there was no quoting.. will fix differently then.

**Pull request merged**
