### PR TITLE
Install the SUSE theme when site_branding is SUSE related

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by vuntz** [comment]
+1 on the code, but I'm wondering if it could be something we want to enforce in the package instead (always install the theme).

**Comment by toabctl** [comment]
@dirkmueller you told me that apache should be restarted after the installation and you don't want to have it in the package, so I guess this is the right PR to add this, too.

**Comment by toabctl** [comment]
> +1 on the code, but I'm wondering if it could be something we want to enforce in the package instead (always install the theme).

Seems that there are openSUSE users who want to have the upstream branding. That's why it isn't enforced in the package itself.

**Comment by vuntz** [comment]
@toabctl I meant the barclamp-nova_dashboard package :-) We could enforce this theme as a distro patch in the product.

**Comment by dirkmueller** [comment]
@vuntz well, this way a user can change the site branding to something else and he won't get the suse theme installed. its more flexible this way over a forced patch in the package. I think many bigger installations will prefer to run their own branding.

**Comment by dirkmueller** [comment]
the new version with the apache reload isn't tested yet

**Comment by toabctl** [comment]
+1

**Comment by vuntz** [comment]
Okay with me for the package not being required. The other bit I'm unsure about is if we want to base the fact that we install this package on the fact that a string contains SUSE. This seems somehow wrong to me as we give two meanings to one attribute.

Would it be an option to add a /srv/www/openstack-dashboard/openstack_dashboard/local/local_settings_theme.py file to the theme package, that we would import from local_settings.py:

```python
try:
    from local_settings_theme import *  # noqa
except ImportError:
    logging.debug("No local_settings_theme file found.")
```

This file would only contain `SITE_BRANDING = "SUSE Cloud"`.

We would also drop the site_branding key, and instead use a new attribute to pick which theme to install.

(We could work on this after this PR is merged, though)

**Comment by dirkmueller** [comment]
@vuntz we can just add an additional attribute for selecting the theme instead of using the site branding name for that.

**Comment by dirkmueller** [comment]
@vuntz SITE_BRANDING has a 2nd meaning, its the title of the webpages. so I would not like to remove that. 

how about this patch instead?

**Comment by vuntz** [comment]
+1

**Comment by toabctl** [comment]
+1

**Pull request merged**
