### PR TITLE
Check for the certificate file (bsc#960006)

### PR DESCRIPTION
**Pull request by bhdn**
This picks only the check in "Move check for certificate file earlier" from
crowbar-openstack.

### CODE REVIEW

**Comment by vuntz** [comment]
+1, but can you link to the pull request from crowbar-openstack in the commit message?

**Comment by bhdn** [comment]
The PR has been updated to have the link.

**Comment by vuntz** [comment]
Anyone else for a second +1?

**Comment by toabctl** [comment]
+1. Thanks!

**Pull request merged**
