### PR TITLE
Enable the POLICY_FILES setting configuration.

### PR DESCRIPTION
**Pull request by aplanas**
Add six new fields to configure POLICY_FILES dictionary in Horizon
settings (local_settings.py) file.

(cherry picked from commit 527bb4a3e409f8ea2017170d0a07ea9df4cfe9db)
(cherry picked from commit 4237bc3a7fbf1fddb5e9fdfc0f7661a8e67811b4)

### CODE REVIEW

**Comment by bmwiedemann** [comment]
For some reason I had to delete the horizon proposal and create a new one to get the policy json values. How do I test the migrations properly?

**Comment by aplanas** [comment]
Uhm not sure to understand. Json policy files are in the different packages.  In the case of Horizon they are in openstack-dashboard-2014.2*

**Comment by vuntz** [comment]
@aplanas I'd somehow feel more comfortable if the two cherry-picked commits were not merged as one. Not sure if it's just me, though?

**Comment by aplanas** [comment]
@vuntz I agree, but basically https://github.com/crowbar/barclamp-nova_dashboard/commit/527bb4a3e409f8ea2017170d0a07ea9df4cfe9db is introducing an error fixed in https://github.com/crowbar/barclamp-nova_dashboard/commit/4237bc3a7fbf1fddb5e9fdfc0f7661a8e67811b4

**Comment by vuntz** [comment]
Can you add https://github.com/crowbar/barclamp-nova_dashboard/pull/222 too?

**Comment by aplanas** [comment]
* Separate cherry-picks
* Add https://github.com/crowbar/barclamp-nova_dashboard/pull/222

**Comment by vuntz** [comment]
+1

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
